{% set name = "kikuchipy" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1cf163afd7d001877fe6859af3a6c7d5f395ceece22eb3fc71bcbca2aeb30925

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - dask >=2021.8.1
    - diffpy.structure >=3
    - diffsims >=0.5
    - hyperspy-base >=1.7
    - h5py
    - matplotlib-base
    - numpy
    - numba
    - orix >=0.9
    - pooch
    - pyvista
    - tqdm
    - scikit-image
    - scikit-learn
    - scipy

test:
  requires:
    - coverage
    - pytest
    - pytest-cov
  imports:
    - kikuchipy
    - kikuchipy.crystallography
    - kikuchipy.data
    - kikuchipy.detectors
    - kikuchipy.draw
    - kikuchipy.filters
    - kikuchipy.generators
    - kikuchipy.indexing
    - kikuchipy.io
    - kikuchipy.pattern
    - kikuchipy.pattern.chunk
    - kikuchipy.projections
    - kikuchipy.signals
    - kikuchipy.simulations
    - kikuchipy.release
    - kikuchipy._rotation
    - kikuchipy._util
  commands:
    - pytest --pyargs kikuchipy

about:
  home: https://kikuchipy.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: |
    Python library for processing and analysis of electron backscatter
    diffraction (EBSD) patterns
  description: |
    kikuchipy [ki-ko-chi-pai] is an open-source Python library for processing
    and analysis of electron backscatter diffraction (EBSD) patterns. The
    library builds on the tools for multi-dimensional data analysis provided by
    the HyperSpy library.
  doc_url: https://kikuchipy.org
  dev_url: https://github.com/pyxem/kikuchipy

extra:
  recipe-maintainers:
    - hakonanes
