{% set name = "kikuchipy" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0dae9eccd6570027f95fd86205c45c672f0cf6143661588ab7f7ccf9ee6b9a33

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - dask >=2021.8.1
    - diffpy.structure >=3
    - diffsims >=0.4
    - hyperspy-base >=1.6.5
    - h5py
    - matplotlib-base
    - numpy
    - numba
    - orix >=0.7
    - pooch
    - tqdm
    - scikit-image
    - scikit-learn
    - scipy

test:
  requires:
    - coverage
    - pytest
    - pytest-cov
  imports:
    - kikuchipy
    - kikuchipy.crystallography
    - kikuchipy.data
    - kikuchipy.detectors
    - kikuchipy.draw
    - kikuchipy.filters
    - kikuchipy.generators
    - kikuchipy.indexing
    - kikuchipy.io
    - kikuchipy.pattern
    - kikuchipy.pattern.chunk
    - kikuchipy.projections
    - kikuchipy.signals
    - kikuchipy.simulations
    - kikuchipy.release
    - kikuchipy._rotation
    - kikuchipy._util
  commands:
    - pytest --pyargs kikuchipy

about:
  home: https://kikuchipy.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: |
    Python library for processing and analysis of electron backscatter diffraction (EBSD) patterns
  doc_url: https://kikuchipy.org
  dev_url: https://github.com/pyxem/kikuchipy

extra:
  recipe-maintainers:
    - hakonanes
