{% set name = "kikuchipy" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1e7314ca80f29febe5691aeee038ddefb806b5487e2f9a1797e94e0924775b3f

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - dask
    - hyperspy >=1.5.2
    - h5py
    - matplotlib
    - numpy >=1.17
    - pyxem >=0.10
    - scikit-image >0.16,< 0.17
    - scikit-learn
    - scipy

test:
  requires:
    - pytest >=5.3.2
  imports:
    - kikuchipy
  commands:
    - pytest --pyargs kikuchipy

about:
  home: https://github.com/kikuchipy/kikuchipy
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: |
    KikuchiPy is an open-source Python library for processing and analysis of
    electron backscatter diffraction (EBSD) patterns
  doc_url: https://kikuchipy.readthedocs.io/
  dev_url: https://github.com/kikuchipy/kikuchipy

extra:
  recipe-maintainers:
    - hakonanes
