{% set name = "kikuchipy" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c0ee55a6b1e351ce6f2192140d62771d34a01c1c91ab2a49453e8d11b9b683ed

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3,<3.9
  run:
    - python >=3,<3.9
    - dask
    - diffpy.structure >=3
    - diffsims >=0.4
    - hyperspy-base >=1.5.2
    - h5py
    - matplotlib-base
    - numpy
    - numba
    - orix >=0.5
    - pooch
    - psutil
    - tqdm
    - scikit-image
    - scikit-learn
    - scipy

test:
  requires:
    - coverage
    - pytest
    - pytest-cov
  imports:
    - kikuchipy
    - kikuchipy.crystallography
    - kikuchipy.data
    - kikuchipy.detectors
    - kikuchipy.draw
    - kikuchipy.filters
    - kikuchipy.generators
    - kikuchipy.indexing
    - kikuchipy.io
    - kikuchipy.pattern
    - kikuchipy.pattern.chunk
    - kikuchipy.projections
    - kikuchipy.signals
    - kikuchipy.simulations
    - kikuchipy.release
  commands:
    - pytest --pyargs kikuchipy

about:
  home: https://kikuchipy.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: |
    kikuchipy is an open-source Python library for processing and analysis of
    electron backscatter diffraction (EBSD) patterns
  doc_url: https://kikuchipy.org
  dev_url: https://github.com/pyxem/kikuchipy

extra:
  recipe-maintainers:
    - hakonanes
