{% set name = "kikuchipy" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f0523ac0245d59c598fbaa0c62da46e5b08de306a62a7a99d4c140cc422772be

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - dask-core >=2021.8.1
    - diffpy.structure >=3
    - diffsims >=0.5.1
    - hyperspy-base >=1.7.3,<2
    - h5py
    - imageio
    - matplotlib-base
    - nlopt
    - numpy
    - numba >=0.55
    - orix >=0.11.1
    - pooch
    - pyebsdindex-base ~=0.2
    - pyyaml
    - scikit-image
    - scikit-learn
    - scipy
    - tqdm

test:
  requires:
    - coverage
    - pytest
    - pytest-cov
    - pytest-xdist
    - pytest-rerunfailures
  imports:
    - kikuchipy
    - kikuchipy.data
    - kikuchipy.detectors
    - kikuchipy.draw
    - kikuchipy.filters
    - kikuchipy.imaging
    - kikuchipy.indexing
    - kikuchipy.io
    - kikuchipy.pattern
    - kikuchipy.signals
    - kikuchipy.simulations
    - kikuchipy.release
    - kikuchipy._rotation
    - kikuchipy._util
  commands:
    - pytest --pyargs kikuchipy -n 2 --reruns 2

about:
  home: https://kikuchipy.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: |
    Processing, simulating and indexing of electron backscatter diffraction
    (EBSD) patterns
  description: |
    kikuchipy [ki-ko-chi-pai] is a library for processing, simulating
    and indexing of electron backscatter diffraction (EBSD) patterns in
    Python, built on the tools for multi-dimensional data analysis
    provided by the HyperSpy library.
  doc_url: https://kikuchipy.org
  dev_url: https://github.com/pyxem/kikuchipy

extra:
  recipe-maintainers:
    - hakonanes
