{% set name = "kikuchipy" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 34580e82984d9bbd105d9d62f09cad6560edb18f10e260dfb4a6fcac2a049427

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - dask >=2021.8.1
    - diffpy.structure >=3
    - diffsims >=0.5
    - hyperspy-base >=1.7
    - h5py
    - imageio
    - matplotlib-base
    - numpy
    - numba
    - orix >=0.9
    # TODO: Remove in next conda-forge release after 0.7.0
    - pint <=0.19
    - pooch
    - pyyaml
    - pyvista
    - scikit-image
    - scikit-learn
    - scipy
    - tqdm

test:
  requires:
    - coverage
    - pytest
    - pytest-cov
  imports:
    - kikuchipy
    - kikuchipy.crystallography
    - kikuchipy.data
    - kikuchipy.detectors
    - kikuchipy.draw
    - kikuchipy.filters
    - kikuchipy.generators
    - kikuchipy.indexing
    - kikuchipy.io
    - kikuchipy.pattern
    - kikuchipy.pattern.chunk
    - kikuchipy.projections
    - kikuchipy.signals
    - kikuchipy.simulations
    - kikuchipy.release
    - kikuchipy._rotation
    - kikuchipy._util
  commands:
    - pytest --pyargs kikuchipy

about:
  home: https://kikuchipy.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: |
    Python library for processing and analysis of electron backscatter
    diffraction (EBSD) patterns
  description: |
    kikuchipy [ki-ko-chi-pai] is a library for processing, simulating
    and analyzing electron backscatter diffraction (EBSD) patterns in
    Python, built on the tools for multi-dimensional data analysis
    provided by the HyperSpy library.
  doc_url: https://kikuchipy.org
  dev_url: https://github.com/pyxem/kikuchipy

extra:
  recipe-maintainers:
    - hakonanes
