{% set name = "kikuchipy" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5245bb11fa7d086af412c15f6791316478f89154fc21f3654b923006e24231f3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3,<3.9
  run:
    - python >=3,3.9
    - dask
    - diffsims >=0.4
    - hyperspy-base >=1.5.2
    - h5py >=2.10
    - matplotlib-base >=3.2
    - numpy >=1.18
    - numba >=0.48
    - orix >=0.5
    - pooch >=0.13
    - psutil
    - tqdm >=0.5.2
    - scikit-image >=0.16
    - scikit-learn
    - scipy

test:
  requires:
    - coverage >=5.0
    - pytest >=5.3.2
    - pytest-cov >=2.8.1
  imports:
    - kikuchipy
    - kikuchipy.crystallography
    - kikuchipy.data
    - kikuchipy.detectors
    - kikuchipy.draw
    - kikuchipy.filters
    - kikuchipy.generators
    - kikuchipy.indexing
    - kikuchipy.io
    - kikuchipy.pattern
    - kikuchipy.pattern.chunk
    - kikuchipy.projections
    - kikuchipy.signals
    - kikuchipy.simulations
    - kikuchipy.release
  commands:
    - pytest --pyargs kikuchipy

about:
  home: https://kikuchipy.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: |
    kikuchipy is an open-source Python library for processing and analysis of
    electron backscatter diffraction (EBSD) patterns
  doc_url: https://kikuchipy.org
  dev_url: https://github.com/pyxem/kikuchipy

extra:
  recipe-maintainers:
    - hakonanes
