{% set name = "kikuchipy" %}
{% set version = "0.11.1.post0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6008c5892a6927f7b0a04e1e0a30fde3855817ebb6cdffb5a49cfda553c7294b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - dask-core >=2021.8.1
    - diffpy.structure >=3
    - diffsims >=0.5.2
    - hyperspy-base >=2.2
    - h5py
    - imageio
    - matplotlib-base
    - nlopt
    - numpy
    - numba >=0.57
    - orix-base
    - pooch
    - pyebsdindex-base >=0.2,!=0.3.0,!=0.3.1
    - pyyaml
    - rosettasciio
    - scikit-image
    - scikit-learn
    - scipy
    - tqdm

test:
  requires:
    - python {{ python_min }}
    - coverage
    - pytest
    - pytest-cov
    - pytest-xdist
    - pytest-rerunfailures
  source_files:
    - tests
    - conftest.py
  imports:
    - kikuchipy
    - kikuchipy.data
    - kikuchipy.detectors
    - kikuchipy.draw
    - kikuchipy.filters
    - kikuchipy.imaging
    - kikuchipy.indexing
    - kikuchipy.io
    - kikuchipy.pattern
    - kikuchipy.signals
    - kikuchipy.simulations
  commands:
    - pytest tests -n 2 --reruns 2 -k "not test_imaging and not test_io and not test_signals"
    - pip check

about:
  home: https://kikuchipy.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: |
    Processing, simulating, and indexing of electron backscatter diffraction (EBSD)
    patterns
  description: |
    kikuchipy is a library for processing, simulating, and indexing of electron
    backscatter diffraction (EBSD) patterns in Python, built on the tools for
    multi-dimensional data analysis provided by the HyperSpy library.
  doc_url: https://kikuchipy.org
  dev_url: https://github.com/pyxem/kikuchipy

extra:
  recipe-maintainers:
    - hakonanes
