{% set name = "kikuchipy" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 01fc053ea7c6acea4816e8bfbd31c9baa982b1b858812104ff46a4a98afa6a99

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - dask >=2021.8.1
    - diffpy.structure >=3
    - diffsims >=0.5
    - hyperspy-base >=1.7.3
    - h5py
    - imageio
    - matplotlib-base
    - nlopt
    - numpy
    - numba
    - orix >=0.11
    - pooch
    - pyebsdindex >=0.1.1
    - pyyaml
    - pyvista
    - scikit-image
    - scikit-learn
    - scipy
    - tqdm

test:
  requires:
    - coverage
    - pytest
    - pytest-cov
  imports:
    - kikuchipy
    - kikuchipy.crystallography
    - kikuchipy.data
    - kikuchipy.detectors
    - kikuchipy.draw
    - kikuchipy.filters
    - kikuchipy.generators
    - kikuchipy.imaging
    - kikuchipy.indexing
    - kikuchipy.io
    - kikuchipy.pattern
    - kikuchipy.pattern.chunk
    - kikuchipy.projections
    - kikuchipy.signals
    - kikuchipy.simulations
    - kikuchipy.release
    - kikuchipy._rotation
    - kikuchipy._util
  commands:
    - pytest --pyargs kikuchipy

about:
  home: https://kikuchipy.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: |
    Processing, simulating and indexing of electron backscatter diffraction
    (EBSD) patterns
  description: |
    kikuchipy [ki-ko-chi-pai] is a library for processing, simulating
    and analyzing electron backscatter diffraction (EBSD) patterns in
    Python, built on the tools for multi-dimensional data analysis
    provided by the HyperSpy library.
  doc_url: https://kikuchipy.org
  dev_url: https://github.com/pyxem/kikuchipy

extra:
  recipe-maintainers:
    - hakonanes
