{% set name = "kikuchipy" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2b03a20deb396bc3510bcc2d564422e82e1d552848f8f07e1b9a9b4c95189af6

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - dask[array]
    - hyperspy[learning] >=1.5.2
    - h5py
    - matplotlib
    - numpy >=1.17
    - pyxem >=0.10
    - scikit-image >0.16,<0.17
    - scipy

test:
  requires:
    - pytest >=5.3.2
  imports:
    - kikuchipy
  commands:
    - pytest --pyargs kikuchipy

about:
  home: https://kikuchipy.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: |
    kikuchipy is an open-source Python library for processing and analysis of
    electron backscatter diffraction (EBSD) patterns
  doc_url: https://kikuchipy.org
  dev_url: https://github.com/kikuchipy/kikuchipy

extra:
  recipe-maintainers:
    - hakonanes
